#!/bin/bash

## Created By Aditya Shakya

MENU="$(rofi -sep "|" -dmenu -i -p 'System' -location 3 -yoffset 60 -xoffset \
    -28 -width 15 -hide-scrollbar -line-padding 5 -padding 20 -lines 4 -font \
    "Fantasque Sans Mono 11" <<< \
    " Lock| Lock & Screen Off| Reboot| Shutdown")"
            case "$MENU" in
                *Lock) ~/.config/i3/i3lock-fancy-multimonitor/lock -b=0x8;;
                *"Lock & Screen Off")
                        ~/.config/i3/i3lock-fancy-multimonitor/lock -b=0x8;
                        xset dpms force off;;
                *Reboot) systemctl reboot ;;
                *Shutdown) systemctl -i poweroff
            esac
